<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="9" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="52395" started-at="2020-05-26T00:31:16 IST" finished-at="2020-05-26T00:32:09 IST">
    <groups>
    </groups>
    <test name="Test1" duration-ms="19315" started-at="2020-05-26T00:31:16 IST" finished-at="2020-05-26T00:31:36 IST">
      <class name="com.appname.testcases.SampleClass">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.appname.testcases.SampleClass@6ab778a]" name="setUp" is-config="true" duration-ms="7788" started-at="2020-05-26T00:31:17 IST" finished-at="2020-05-26T00:31:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="sampleTestCase_01()[pri:0, instance:com.appname.testcases.SampleClass@6ab778a]" name="sampleTestCase_01" duration-ms="2648" started-at="2020-05-26T00:31:24 IST" finished-at="2020-05-26T00:31:27 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.appname.testcases.SampleClass.sampleTestCase_01(SampleClass.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_01 -->
        <test-method status="PASS" signature="sampleTestCase_02()[pri:0, instance:com.appname.testcases.SampleClass@6ab778a]" name="sampleTestCase_02" duration-ms="2466" started-at="2020-05-26T00:31:27 IST" finished-at="2020-05-26T00:31:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_02 -->
        <test-method status="FAIL" signature="sampleTestCase_03()[pri:0, instance:com.appname.testcases.SampleClass@6ab778a]" name="sampleTestCase_03" duration-ms="1167" started-at="2020-05-26T00:31:30 IST" finished-at="2020-05-26T00:31:31 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.appname.testcases.SampleClass.sampleTestCase_03(SampleClass.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_03 -->
        <test-method status="PASS" signature="sampleTestCase_04()[pri:0, instance:com.appname.testcases.SampleClass@6ab778a]" name="sampleTestCase_04" duration-ms="1219" started-at="2020-05-26T00:31:32 IST" finished-at="2020-05-26T00:31:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_04 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.appname.testcases.SampleClass@6ab778a]" name="tearDown" is-config="true" duration-ms="2789" started-at="2020-05-26T00:31:33 IST" finished-at="2020-05-26T00:31:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.appname.testcases.SampleClass -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="14569" started-at="2020-05-26T00:31:37 IST" finished-at="2020-05-26T00:31:51 IST">
      <class name="com.appname.testcases.SampleClass2">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.appname.testcases.SampleClass2@5609159b]" name="setUp" is-config="true" duration-ms="5782" started-at="2020-05-26T00:31:37 IST" finished-at="2020-05-26T00:31:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="sampleTestCase_05()[pri:0, instance:com.appname.testcases.SampleClass2@5609159b]" name="sampleTestCase_05" duration-ms="5553" started-at="2020-05-26T00:31:43 IST" finished-at="2020-05-26T00:31:48 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.appname.testcases.SampleClass2.sampleTestCase_05(SampleClass2.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_05 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.appname.testcases.SampleClass2@5609159b]" name="tearDown" is-config="true" duration-ms="2793" started-at="2020-05-26T00:31:49 IST" finished-at="2020-05-26T00:31:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.appname.testcases.SampleClass2 -->
    </test> <!-- Test2 -->
    <test name="Test3" duration-ms="17245" started-at="2020-05-26T00:31:51 IST" finished-at="2020-05-26T00:32:09 IST">
      <class name="com.appname.testcases.SampleClass3">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.appname.testcases.SampleClass3@fa36558]" name="setUp" is-config="true" duration-ms="5801" started-at="2020-05-26T00:31:51 IST" finished-at="2020-05-26T00:31:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="sampleTestCase_06(java.util.Map)[pri:0, instance:com.appname.testcases.SampleClass3@fa36558]" name="sampleTestCase_06" duration-ms="3323" started-at="2020-05-26T00:31:58 IST" data-provider="DataSupplier" finished-at="2020-05-26T00:32:02 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Akansh, password=Jha}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.appname.testcases.SampleClass3.sampleTestCase_06(SampleClass3.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_06 -->
        <test-method status="PASS" signature="sampleTestCase_06(java.util.Map)[pri:0, instance:com.appname.testcases.SampleClass3@fa36558]" name="sampleTestCase_06" duration-ms="1584" started-at="2020-05-26T00:32:02 IST" data-provider="DataSupplier" finished-at="2020-05-26T00:32:04 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Mukul, password=Talwar}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_06 -->
        <test-method status="PASS" signature="sampleTestCase_06(java.util.Map)[pri:0, instance:com.appname.testcases.SampleClass3@fa36558]" name="sampleTestCase_06" duration-ms="1123" started-at="2020-05-26T00:32:04 IST" data-provider="DataSupplier" finished-at="2020-05-26T00:32:05 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Ashish, password=Singh}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_06 -->
        <test-method status="PASS" signature="sampleTestCase_06(java.util.Map)[pri:0, instance:com.appname.testcases.SampleClass3@fa36558]" name="sampleTestCase_06" duration-ms="1028" started-at="2020-05-26T00:32:05 IST" data-provider="DataSupplier" finished-at="2020-05-26T00:32:06 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Riya, password=Sonune}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_06 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.appname.testcases.SampleClass3@fa36558]" name="tearDown" is-config="true" duration-ms="2846" started-at="2020-05-26T00:32:06 IST" finished-at="2020-05-26T00:32:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.appname.testcases.SampleClass3 -->
    </test> <!-- Test3 -->
  </suite> <!-- Suite -->
</testng-results>
