<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="9" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="39113" started-at="2020-05-30T21:06:57 IST" finished-at="2020-05-30T21:07:36 IST">
    <groups>
    </groups>
    <test name="Test1" duration-ms="14410" started-at="2020-05-30T21:06:57 IST" finished-at="2020-05-30T21:07:12 IST">
      <class name="com.appname.testcases.SampleClass">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.appname.testcases.SampleClass@15ca7889]" name="setUp" is-config="true" duration-ms="6462" started-at="2020-05-30T21:06:57 IST" finished-at="2020-05-30T21:07:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="sampleTestCase_01()[pri:0, instance:com.appname.testcases.SampleClass@15ca7889]" name="sampleTestCase_01" duration-ms="1305" started-at="2020-05-30T21:07:04 IST" finished-at="2020-05-30T21:07:05 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.appname.testcases.SampleClass.sampleTestCase_01(SampleClass.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_01 -->
        <test-method status="PASS" signature="sampleTestCase_02()[pri:0, instance:com.appname.testcases.SampleClass@15ca7889]" name="sampleTestCase_02" duration-ms="1625" started-at="2020-05-30T21:07:06 IST" finished-at="2020-05-30T21:07:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_02 -->
        <test-method status="FAIL" signature="sampleTestCase_03()[pri:0, instance:com.appname.testcases.SampleClass@15ca7889]" name="sampleTestCase_03" duration-ms="708" started-at="2020-05-30T21:07:07 IST" finished-at="2020-05-30T21:07:08 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.appname.testcases.SampleClass.sampleTestCase_03(SampleClass.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_03 -->
        <test-method status="PASS" signature="sampleTestCase_04()[pri:0, instance:com.appname.testcases.SampleClass@15ca7889]" name="sampleTestCase_04" duration-ms="765" started-at="2020-05-30T21:07:08 IST" finished-at="2020-05-30T21:07:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_04 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.appname.testcases.SampleClass@15ca7889]" name="tearDown" is-config="true" duration-ms="2783" started-at="2020-05-30T21:07:09 IST" finished-at="2020-05-30T21:07:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.appname.testcases.SampleClass -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="9834" started-at="2020-05-30T21:07:12 IST" finished-at="2020-05-30T21:07:22 IST">
      <class name="com.appname.testcases.SampleClass2">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.appname.testcases.SampleClass2@37f1104d]" name="setUp" is-config="true" duration-ms="5468" started-at="2020-05-30T21:07:12 IST" finished-at="2020-05-30T21:07:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="sampleTestCase_05()[pri:0, instance:com.appname.testcases.SampleClass2@37f1104d]" name="sampleTestCase_05" duration-ms="1256" started-at="2020-05-30T21:07:18 IST" finished-at="2020-05-30T21:07:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.appname.testcases.SampleClass2.sampleTestCase_05(SampleClass2.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_05 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.appname.testcases.SampleClass2@37f1104d]" name="tearDown" is-config="true" duration-ms="2756" started-at="2020-05-30T21:07:19 IST" finished-at="2020-05-30T21:07:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.appname.testcases.SampleClass2 -->
    </test> <!-- Test2 -->
    <test name="Test3" duration-ms="14453" started-at="2020-05-30T21:07:22 IST" finished-at="2020-05-30T21:07:36 IST">
      <class name="com.appname.testcases.SampleClass3">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.appname.testcases.SampleClass3@2a266d09]" name="setUp" is-config="true" duration-ms="5432" started-at="2020-05-30T21:07:22 IST" finished-at="2020-05-30T21:07:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="sampleTestCase_06(java.util.Map)[pri:0, instance:com.appname.testcases.SampleClass3@2a266d09]" name="sampleTestCase_06" duration-ms="890" started-at="2020-05-30T21:07:28 IST" data-provider="DataSupplier" finished-at="2020-05-30T21:07:29 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Akansh, password=Jha}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.appname.testcases.SampleClass3.sampleTestCase_06(SampleClass3.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_06 -->
        <test-method status="PASS" signature="sampleTestCase_06(java.util.Map)[pri:0, instance:com.appname.testcases.SampleClass3@2a266d09]" name="sampleTestCase_06" duration-ms="1619" started-at="2020-05-30T21:07:29 IST" data-provider="DataSupplier" finished-at="2020-05-30T21:07:31 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Mukul, password=Talwar}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_06 -->
        <test-method status="PASS" signature="sampleTestCase_06(java.util.Map)[pri:0, instance:com.appname.testcases.SampleClass3@2a266d09]" name="sampleTestCase_06" duration-ms="2341" started-at="2020-05-30T21:07:31 IST" data-provider="DataSupplier" finished-at="2020-05-30T21:07:33 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Ashish, password=Singh}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_06 -->
        <test-method status="PASS" signature="sampleTestCase_06(java.util.Map)[pri:0, instance:com.appname.testcases.SampleClass3@2a266d09]" name="sampleTestCase_06" duration-ms="722" started-at="2020-05-30T21:07:33 IST" data-provider="DataSupplier" finished-at="2020-05-30T21:07:34 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Riya, password=Sonune}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase_06 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.appname.testcases.SampleClass3@2a266d09]" name="tearDown" is-config="true" duration-ms="2744" started-at="2020-05-30T21:07:34 IST" finished-at="2020-05-30T21:07:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.appname.testcases.SampleClass3 -->
    </test> <!-- Test3 -->
  </suite> <!-- Suite -->
</testng-results>
